spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect

itemImgLocation: /Users/tmdwns/Desktop/develop/shop/item
uploadPath: file:////Users/tmdwns/Desktop/develop/shop/